<?php

return [
    [
        'key'    => 'sales.payment_methods.clickpesa',
        'name'   => 'ClickPesa',
        'info'   => 'ClickPesa payment configuration',
        'sort'   => 1,
        'fields' => [
            [
                'name'          => 'active',
                'title'         => 'Enable',
                'type'          => 'boolean',
                'validation'    => 'required',
                'default'       => false,
                'channel_based' => false,
                'locale_based'  => true,
            ],
            [
                'name'          => 'title',
                'title'         => 'Title',
                'type'          => 'text',
                'validation'    => 'required_if:active,1',
                'default'       => 'ClickPesa',
                'channel_based' => false,
                'locale_based'  => true,
            ],
            [
                'name'          => 'description',
                'title'         => 'Payment Method Description',
                'type'          => 'textarea',
                'depend'        => 'active:1',
                'channel_based' => false,
                'locale_based'  => true,
                'default'       => 'Pay securely with ClickPesa',
            ],
            [
                'name'          => 'client_id',
                'title'         => 'Client ID',
                'type'          => 'text',
                'validation'    => 'required_if:active,1',
                'default'       => '',
                'channel_based' => false,
                'locale_based'  => true,
            ],
            [
                'name'          => 'api_secret',
                'title'         => 'API Secret',
                'type'          => 'password',
                'validation'    => 'required_if:active,1',
                'default'       => '',
                'channel_based' => false,
                'locale_based'  => true,
            ],
            [
                'name'          => 'checksum_key',
                'title'         => 'Checksum Key',
                'type'          => 'password',
                'validation'    => 'required_if:active,1',
                'default'       => '',
                'channel_based' => false,
                'locale_based'  => true,
            ],
            [
                'name'          => 'api_url',
                'title'         => 'API URL',
                'type'          => 'text',
                'validation'    => 'required_if:active,1|url',
                'default'       => 'https://api.clickpesa.com',
                'channel_based' => false,
                'locale_based'  => true,
            ],
            [
                'name'          => 'return_url',
                'title'         => 'Return URL',
                'type'          => 'text',
                'validation'    => 'required_if:active,1|url',
                'default'       => 'https://your-domain.com/clickpesa/success',
                'channel_based' => false,
                'locale_based'  => true,
            ],
            [
                'name'          => 'webhook_secret',
                'title'         => 'Webhook Secret',
                'type'          => 'password',
                'validation'    => 'required_if:active,1',
                'default'       => '',
                'channel_based' => false,
                'locale_based'  => true,
            ],
            [
                'name'          => 'sort',
                'title'         => 'Sort Order',
                'type'          => 'text',
                'channel_based' => false,
                'locale_based'  => true,
            ],
        ],
    ],
];
